In [2]:
#Exp_3

In [3]:
#Aim: Creating the Dataframe

In [1]:
#Name:Om V. Satpute
#Roll no:54
#Sec:B
#Subject:ET-1

# Creating Series

In [2]:
import pandas as pd

In [3]:
Name=["Pratik","Govind","Shubham","Dev","Vedant"]

In [4]:
Name

['Pratik', 'Govind', 'Shubham', 'Dev', 'Vedant']

In [5]:
Roll_list=pd.Series(Name,index=[1,2,3,4,5])
print(Roll_list)

1     Pratik
2     Govind
3    Shubham
4        Dev
5     Vedant
dtype: object

# Creating a Data Frame

In [6]:
df=pd.DataFrame([[10,13,15,18],[17,16,19,12],[11,12,14,17]],
                columns= ["CD","DBMS","DSS","CAO"])

In [7]:
df

   CD  DBMS  DSS  CAO
0  10    13   15   18
1  17    16   19   12
2  11    12   14   17

In [8]:
df.shape

(3, 4)

In [9]:
df.size

12

In [10]:
df.ndim

2

# Adding Record (Row)to the Data Frame

In [11]:
df2=pd.DataFrame([[6,5,7,9]],
columns= ["CD","DBMS","DSS","CAO"])

In [13]:
df3 =pd.concat([df,df2,df3], ignore_index=True)

NameError: name 'df3' is not defined

In [14]:
df3

NameError: name 'df3' is not defined

# Adding Attribute(Columns) to the Data Frame

In [15]:
df3["DM"]=[12,14,16,18]

NameError: name 'df3' is not defined

In [16]:
df3

NameError: name 'df3' is not defined

# Deleting Record from df3 dataframe

In [41]:
df4=df3.drop(index=[1])

In [42]:
df4

   CD  DBMS  DSS  CAO  DM
0   6     5    7    9  12
2   6     5    7    9  16
3   6     5    7    9  18

# Deleting Attribute (Columns) from df3 dataframe

In [43]:
df5=df3.drop(columns=["DM"])

In [44]:
df5

   CD  DBMS  DSS  CAO
0   6     5    7    9
1   6     5    7    9
2   6     5    7    9
3   6     5    7    9

In [45]:
print("Mean of DSS:",df5["DSS"].mean())

Mean of DSS: 7.0

In [46]:
print("Median of DSS:",df5["DSS"].median())

Median of DSS: 7.0

In [47]:
print("Mode of DSS:",df5["DSS"].mode())

Mode of DSS: 0    7
Name: DSS, dtype: int64